### ISSUE TITLE
Concurrent reading and writing of artifacts in python

### ISSUE THREAD

**Issue by jkoal** [MasonMcGill/artisan#3] opened 2019-06-17 19:10 UTC
Hi Mason,

I have trained a network in one jupyter notebook and simultaneously read out activity data using watchdog in another jupyter notebook to plot the data in real-time. For a few iterations this works fine but after 20 or so it breaks raising `ValueError: Unable to set extend dataset (no write intent on file)`. Apparently there is some interference between one kernel opening the files for writing and one kernel opening the files for reading? Full traceback below:

```python

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-46-71419ef1d62b> in <module>
      5                            λ_dec = 1e-5,
      6                            n_samples = n_samples,
----> 7                            n_iter = 10_000)

~/miniconda3/envs/dvs-sim/lib/python3.7/site-packages/artisan/_artifacts.py in __new__(cls, *args, **kwargs)
     67             return _artifact_from_path(cls, _resolve_path(path))
     68         elif path is None and conf is not None:
---> 69             return _artifact_from_conf(cls, conf)
     70         elif path is not None and conf is not None:
     71             return _artifact_from_path_and_conf(cls, _resolve_path(path), conf)

~/miniconda3/envs/dvs-sim/lib/python3.7/site-packages/artisan/_artifacts.py in _artifact_from_conf(cls, conf)
    331     else:
    332         object.__setattr__(artifact, 'path', _new_artifact_path(type(artifact)))
--> 333         _build(artifact)
    334         return artifact
    335 

~/miniconda3/envs/dvs-sim/lib/python3.7/site-packages/artisan/_artifacts.py in _build(artifact)
    383     except BaseException as e:
    384         write_meta(spec=spec, status='stopped')
--> 385         raise e
    386 
    387 

~/miniconda3/envs/dvs-sim/lib/python3.7/site-packages/artisan/_artifacts.py in _build(artifact)
    379             n_build_args = artifact.build.__code__.co_argcount
    380             build_args = [artifact.conf] if n_build_args > 1 else []
--> 381             artifact.build(*build_args)
    382         write_meta(spec=spec, status='done')
    383     except BaseException as e:

~/miniconda3/envs/dvs-sim/lib/python3.7/site-packages/dvs/network_training.py in build(self, conf)
     97                 # log aggregated activity
     98                 self.extend('activity', [np.stack([network_states[i].nodes["activity"].detach().cpu()
---> 99                                                    for i in range(len(network_states))], axis=1).mean()])
    100             if t == 0:
    101                 self.ctome = ctome

~/miniconda3/envs/dvs-sim/lib/python3.7/site-packages/artisan/_artifacts.py in extend(self, key, val)
    199         else:
    200             assert path.suffix == ''
--> 201             _extend_h5(path.with_suffix('.h5'), val)
    202 
    203     #-- Attribute-style element access --------------------

~/miniconda3/envs/dvs-sim/lib/python3.7/site-packages/artisan/_artifacts.py in _extend_h5(path, val)
    442     else:
    443         dset = f['data']
--> 444     dset.resize(dset.len() + len(val), 0)
    445     dset[-len(val):] = val
    446     dset.flush()

~/miniconda3/envs/dvs-sim/lib/python3.7/site-packages/h5py/_hl/dataset.py in resize(self, size, axis)
    436 
    437             size = tuple(size)
--> 438             self.id.set_extent(size)
    439             #h5f.flush(self.id)  # THG recommends
    440 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5d.pyx in h5py.h5d.DatasetID.set_extent()

ValueError: Unable to set extend dataset (no write intent on file)
```

**Comment by MasonMcGill** [comment] 2019-06-17 19:34
Hmm. SWMR should prevent issues of this flavor, so I'll have to take a closer look.

**Comment by MasonMcGill** [comment] 2019-07-01 13:01
What HDF5 and H5Py versions are you using? It looks like this could be caused by not having access to HDF5 v1.10.

**Comment by MasonMcGill** [comment] 2019-07-09 16:59
It seems like this was caused by an insufficient HDF5 version, so I'll close this issue.

**Closed by MasonMcGill** 2019-07-09 16:59 UTC
Labels: high priority

**Comment by jkoal** [comment] 2019-07-09 17:52
Thanks! It seems like the hdf5 installation installed by conda alongside h5py was at v1.8.16. After updating h5py and hdf5 using `conda update h5py` I couldn't reproduce the error.

**Comment by MasonMcGill** [comment] 2019-07-10 00:18
Great. And d124dee9e9c8982878b9674c5234d433af1b7297 should resolve the non-deterministic version of this issue.
